import "../styles/global.css";
import "../styles/navbar.css";
import "../styles/navlist.css";
import "../styles/navitem.css";
import "../styles/banner.css";
import "../styles/homeCta.css";
import "../styles/imgContainer.css";
import "../styles/informationContent.css";
import "../styles/mission.css";
import "../styles/aboutCta.css"
import "../styles/footer.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Iteration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
